### ISSUE TITLE
Adminbanned players get altbanned message on login

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#101]
https://github.com/Civcraft/PrisonPearl/blob/master/src/vg/civcraft/mc/prisonpearl/managers/ban/CBanManager.java#L28

**Comment by Maxopoly** [comment]
You could give your ban check MONITOR priority, so it's guaranteed after CBan check.

**Comment by rourke750** [comment]
Lol max no, never ever set any state of anything using monitor.  We can
just remove the kick message
https://github.com/Civcraft/PrisonPearl/blob/master/src/vg/civcraft/mc/prisonpearl/listener/BanListener.java#L52
there since cbanmanagement will handle it.

**Comment by Maxopoly** [comment]
Hmm alright. What's so bad about monitor?

**Comment by ProgrammerDan** [comment]
MONITOR should never alter the event they receive...

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/38376b0929374c6266a022ffed7075e88a49b062
