### ISSUE TITLE
Coal not feeding

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/PrisonPearl#103]
Chest coal levels isnt changing after 2 days.

**Comment by PatchyKnowly** [comment]
Were these pearls reverting as soon as you moved them? I've noticed the same, but as soon as I touched the pearl it reverted to a regular enderpearl.

**Comment by Diet-Cola** [comment]
This was an issue back with #114, forgot to close.  

The issue with the pearls being reverted to regular pearls is that Candyland crashes and when the pearled player logs in, they are basically freed.
