### ISSUE TITLE
Pearled players being freed on restart

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/PrisonPearl#114]
Steps to reproduce:  

1. Pearl a player  
2. Deposit pearl in a chest with coal
3. Wait for server restart
4. On login, pearled player should no longer be imprisoned via /ppl and can jump off of the End Island to randomspawn.

**Comment by rourke750** [comment]
If the player has a bed do they still go to the end? Does the player get
freed only on restart?

**Comment by Vastitas** [comment]
> If the player has a bed do they still go to the end?  

In the instances I've tested, yes however there have been hit and miss cases it seems, I think the reason behind this is because at the time the player is pearled, Candyland hasn't been online.  

> Does the player get freed only on restart?
Yes

**Comment by ProgrammerDan** [comment]
Please check if this is still an issue.

**Comment by rourke750** [comment]
There was only one pearled player in the db. Might need to wait till
tomorrow.

**Comment by Diet-Cola** [comment]
Pearled an alt, will comment back tomorrow

**Comment by Diet-Cola** [comment]
Server just restarted, alt account wasn't released.
