### ISSUE TITLE
/ppsummon and /ppreturn returns an error

### ISSUE THREAD

**Issue by Link2006** [Civcraft/PrisonPearl#115]
Whenever you try to /ppsummon a pearled player, an error in chat writes "An internal error has occured..." 

Steps to reproduce:

1) Pearl a player
2) hold the pearl and try to use /ppsummon
3) while still holding the same pearl, try to use /ppreturn.

**Comment by ProgrammerDan** [comment]
Thanks for the report -- please check if this is still an issue.

**Comment by Link2006** [comment]
The issue has been fixed, Thank you.
