### ISSUE TITLE
ppsummon results in the player not being teleported

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/PrisonPearl#116]
Steps to reproduce:  

1. /ppsummon  

The pearled player will stay in the end however immediately after /ppsummon is issued, the player beings to receive damage from being too far away from their pearl. Upon respawn this will continue.  

/ppreturn issues a "The player is offline, cannot be returned safely" in chat and does nothing to stop the pearled player taking constant damage.

**Comment by Diet-Cola** [comment]
Uh, noticing weird behaviour with this one, just re-pearled my alt and PPSummon now works as intended?

**Comment by rourke750** [comment]
Huh weird. Try see if you can reproduce before behavior.

**Comment by ProgrammerDan** [comment]
@Diet-Cola if you can't reproduce might be related to being pearled before a restart and summoned after vs. being pearled and summoned during the same uptime.

**Comment by Diet-Cola** [comment]
Doing /ppsummon while the pearled player is still on the respawn screen results in the pearl holder getting an internal error.  

when the pearled player respawns, they respawn at 0,0 in the world of the pearl holder.  

/ppreturn results in another internal error and the player is not sent back to candyland.  Just keep respawning at 0,0.
