### ISSUE TITLE
Item selected in hotbar when being summoned gets deleted

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/PrisonPearl#121]
Steps to repro:  

1. Hold an item on pearled player  
2. Have pearl holder summon / free
3. Upon coming into the overworld, that slot item will have been deleted

**Comment by rourke750** [comment]
Wait so this happens to the prisoner?

**Comment by Diet-Cola** [comment]
yes

**Comment by rourke750** [comment]
Is this still the case?

**Comment by Diet-Cola** [comment]
Hasn't happened from the time the issue was opened, closing
