### ISSUE TITLE
/ppl doesn't show the location of the pearl after it was moved to a new server. 

### ISSUE THREAD

**Issue by BlackXnt** [Civcraft/PrisonPearl#124]
It will show the last location the pearl was in the original server before the player holding the pearl moved to a new server.

**Comment by ttk2** [comment]
I think this is intentional, we don't broadcast positions between servers because we want to cut down on mercury traffic as much as possible, although considering how much traffic we use on mercury for other plugins that might be kind of a faint hope here.

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/56ba889263c5cc56f458dcd82ad760867d2fdbd6
