### ISSUE TITLE
/pptoggledamage doesn't work

### ISSUE THREAD

**Issue by Crushtoe** [Civcraft/PrisonPearl#128]
A player that's been summoned and has /pptoggledamage used on them to remove their ability to hurt others can still damage other users.

**Comment by ttk2** [comment]
this one we probably need to fix sooner rather than later.

**Comment by Crushtoe** [comment]
Could end with a prisoner with gear given to them by a player sent in to the end to give it to them being summoned and killing the pearl holder, with the Pearl holder having expected to be able to toggle their ability to hurt others.
