### ISSUE TITLE
/ppsummon sometimes results in the prisoner infinitely dying

### ISSUE THREAD

**Issue by Crushtoe** [Civcraft/PrisonPearl#129]
Twice while testing PrisonPearl, we've had someone infinitely dying when /ppsummon'd. /ppreturn says that person cannot be returned as they are offline, as does /ppkill. /ppsummon will report they are already summoned, and relogging does not fix it.

**Comment by Diet-Cola** [comment]
Seems to happen after the first summon & return event.

**Comment by ttk2** [comment]
more detail please. Exactly how and where do they die, do they die on the server they where summoned to? The Prison world server? do they take damage and then die or just die outright?

**Comment by Diet-Cola** [comment]
After the first summon & return, the prisoner seems to start taking damage when next summoned, damaged in a way as in they are too far from their pearl and this will continue until /ppfree is issued, /ppreturn will do nothing. Even after respawn the imprisoned player will continue to die.

**Comment by Crushtoe** [comment]
It seems to be that they take damage and then die, as they have a few seconds to message.

**Comment by ttk2** [comment]
ok so they are in the summoning world when this occurs and nothing strange happens if they go back to the prison world?

**Comment by Diet-Cola** [comment]
No, past the first time they are ppsummon'd and ppreturn'd these commands no longer begin working as intended.  

Past the first time, when the player is summoned, they begin taking damage in the prison world.  

ppreturn does not fix the issue.

ppfree fixes the issue but involves releasing the pearl.

**Comment by ttk2** [comment]
so they die in a loop in the end even when returned?

**Comment by Crushtoe** [comment]
It won't let you return them. It gives an error saying they're offline.

**Comment by Diet-Cola** [comment]
@ttk2 Yes, /ppreturn returns player is offline

**Comment by rourke750** [comment]
Uh, unable to reproduce.

**Comment by rourke750** [comment]
Would this be maybe after you transfered servers?

**Comment by ttk2** [comment]
@Diet-Cola  can you get this to happen every time?

**Comment by Crushtoe** [comment]
If you want, I can get a recording of it later tonight. Want me to do anything specific so you can get certain information while I'm doing it?

**Comment by Diet-Cola** [comment]
I'll see if I can record a video tonight with an alt

**Comment by Diet-Cola** [comment]
@ttk2 Couldnt reproduce the bug however did record a video outlining a new bug with a summoned player staying in the overworld & failing to be returned: https://youtu.be/Rz8X7uJgCOg

**Comment by rourke750** [comment]
Prob cause I fixed the old one.  Will watch video but I think I already
know the issue.

**Comment by Crushtoe** [comment]
Seemed to of been patched, but as of the latest update, it's happening again

**Comment by Crushtoe** [comment]
[Recorded a video of it in action just now.](https://youtu.be/KaaaD9CCMMM)

**Comment by rourke750** [comment]
Did you check since last restart?

**Comment by Diet-Cola** [comment]
both videos also link in with #122 

Not sure if PP has been disabled temporarily but pearling people is not working as of 14:30pm GMT 25/03
