### ISSUE TITLE
Summoned players should be permanently combat-tagged.

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/PrisonPearl#134]
Would actually make summoning something viable.

**Comment by ProgrammerDan** [comment]
Can you explain further the motivation here? What would this prevent or enable?

**Comment by Diet-Cola** [comment]
Right now, summoning is not a viable tactic when people are pearled because if it is a high profile pearl, they will know just to instantly log out.  

With permanent combat tag on summoned players, this restricts their ability to log out since they'll always be hanging around for 30 seconds after.

**Comment by ProgrammerDan** [comment]
This relates to the bug where if someone logged out after summing, they could log back in and respawn overworld?

That's a bug ... 

Or perhaps I'm misunderstanding. Ideal state is: logging out simply, logs them out. Doesn't free, doesn't cause randomspawn, doesn't change pearl state.

**Comment by Diet-Cola** [comment]
When someone is summoned, they can log out, when they log back in they'll still be overworld however they will be taking damage for being so far away from their pearl (most likely). In that timeframe, they can have friends go to where the summoned player logged off, pearl them and have them freed.  

As far as I understand you cannot return a offline player to the end therefore there is no way to currently prevent this.

**Comment by ProgrammerDan** [comment]
Ok, that's a bug. Mind opening a new top-level with that as a bug listing? 

If they log out and back in, they should return to where they logged out at, or if that location is unavailable or they've been returned, they should respawn in the end.

**Comment by ProgrammerDan** [comment]
Oh, actually, this is already an issue: #131

I'll close this and link to it in 131 for reference.
