### ISSUE TITLE
With max imprisoned set to 1 it alt bans anyone who is released (temporarily)

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/PrisonPearl#150]

**Comment by Maxopoly** [comment]
I dont think the alt banning stuff will work without MiscLog. PP itself doesnt keep track of alts in any way.

**Comment by ProgrammerDan** [comment]
That's what I was thinking too

**Comment by ProgrammerDan** [comment]
@TealNerd So I checked real quick and you should definitely be able to make your own alt-tracker, just whatever you're using currently to track alts (if nothing, get something) should listen and fire the various events as listened to and fired from PrisonPearl in AltManager and AltListener.
