### ISSUE TITLE
Summoning issues

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#161]
Summoning seems to be failing randomly after a few repeated tries. It'll first say "requesting a ppsummon", but not do anything. If you then try /pps again, it will say the player is already summoned and if you try /ppr, it will say the player is offline and cant be returned safely (even though he is online in the end)

**Comment by rourke750** [comment]
Fixed here https://github.com/Civcraft/PrisonPearl/pull/174
