### ISSUE TITLE
Switching shards while holding a pearl breaks things

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/PrisonPearl#170]
I had a pearl of BlackXnt

I switched shards and then did /pps

It said attempting to summon, but didnt do anything

doing pps again said he is already summoned

I then did /ppf and it said "You freed Maxopoly"

???

**Comment by rourke750** [comment]
Should be addressed here https://github.com/Civcraft/PrisonPearl/pull/174 with the fix of https://github.com/Civcraft/PrisonPearl/issues/173 will test.

**Comment by rourke750** [comment]
Fixed
