### ISSUE TITLE
Log successful verification

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#19]
https://github.com/Civcraft/PrisonPearl/blob/master/src/com/untamedears/PrisonPearl/PrisonPearl.java#L267

Could we log why a verification was successful at this code location? It will need a bit of refactoring to get the reason for both successes and failures.

**Comment by rourke750** [comment]
Oh fun.

**Comment by spaceFountain** [comment]
Wops I thought I'd already written something here.

What exactly do you want added to the log? It seems it already logs some of the reasons in verifyHolder.

**Comment by erocs** [comment]
VerifyHolder logs locations where the pearl wasn't found. I'd like to know
where the pearl is for a successful verification.

**Comment by spaceFountain** [comment]
Does [this](https://github.com/Civcraft/PrisonPearl/pull/27) do what you need?

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/b4d66ab67b79d1265e4a1c78ff00b7394fdf27ff
