### ISSUE TITLE
Free pearls beyond a given radius from a specific location

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#20]
In this context PrisonPearl would auto free on restart pearls that where outside of world border (15000 block radius from 0,0) making the center and the radius configurable is trivial and may help with mutliwording later.

**Comment by rourke750** [comment]
Done, need to test and will upload code.

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/879951d492bdb72c9f9b4c8e0705d2257a7886b3

**Comment by ttk2** [comment]
is this built on the build server now?

**Comment by rourke750** [comment]
Yea. Its built against new namelayer so I'll throw it on the testing event
for Saturday.

**Comment by ttk2** [comment]
oh, so no running with Citadel 2.0? that's fine then, how does it do its
math?

**Comment by rourke750** [comment]
Simple distance formula.  Have some other way to do it?

**Comment by ttk2** [comment]
what I mean is that chests can only be placed at integer locations, so 1500
is the radius limit, it just frees if the chest is 1501 away?

**Comment by rourke750** [comment]
Yes. Would you like a player warning as well?

**Comment by ttk2** [comment]
I don't know how it would warn them except perhaps when placing the pearl
into the chest

**Comment by rourke750** [comment]
Pretty much.

**Comment by ttk2** [comment]
I should add this to  your Citadel 3.0 testing server? Also I whitelisted
that is there anything else you need me todo so that you can be ready f or
the event this sunday?

**Comment by rourke750** [comment]
I'm good for Saturday. I'll test this myself.  I'll get jawa to help me the
other jars.

**Comment by ttk2** [comment]
updated readius enforcing prisonpearl is now on the citadel 3.0 testing
server
