### ISSUE TITLE
Free Pearls on server restart when container is inaccessible from 3 sides at World Border

### ISSUE THREAD

**Issue by drjawa** [Civcraft/PrisonPearl#21]
>I hope to get the new PrisonPearl with world border enforcement testing and online in very short order, if you have a world border vault I would suggest paying very close attention to the changelogs in the near future to ensure you don't end up losing your pearls. 

https://www.reddit.com/r/Civcraft/comments/2siqq0/morning_changelog_20150115/

**Comment by rourke750** [comment]
Duplicate

**Comment by drjawa** [comment]
Where is the similar issue?

**Comment by rourke750** [comment]
The one I closed due to being completed hence the comment about testing.

**Comment by drjawa** [comment]
Ahh, I should have used the search
