### ISSUE TITLE
1.8 Error

### ISSUE THREAD

**Issue by Mythcartoonist** [Civcraft/PrisonPearl#24]
I'm getting this error on Spigot 1.8 with the latest build off your jenkins:

19.01 22:15:35 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:314) [spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:354) [spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-320ed92-354449a]
19.01 22:15:35 [Server] INFO at com.untamedears.PrisonPearl.PrisonPearlPlugin.onEnable(PrisonPearlPlugin.java:118) ~[?:?]
19.01 22:15:35 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/World
19.01 22:15:35 [Server] INFO [22:15:35 ERROR]: Error occurred while enabling PrisonPearl v2.2.7 (Is it up to date?)

**Comment by rourke750** [comment]
Yep, unfortunately our builds normally follow what ever civcraft mc version we are on.  I'll set up some dev builds which are built for 1.8

**Comment by Mythcartoonist** [comment]
Thank you, that's very nice of you.

**Comment by rourke750** [comment]
I havent forgotten this.

**Comment by rourke750** [comment]
I got the code done but I need to be home to upload it.

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/tree/1.8
