### ISSUE TITLE
prisonpearlsUUID.txt should record username of the Pearled player as well as UUID

### ISSUE THREAD

**Issue by ariehkovler** [Civcraft/PrisonPearl#28]
prisonpearlsUUID.txt should log the username of the player at time of pearling for ease of administration. It's a pain having to connect accounts to UUIDs manually each time when investigating alt associations.

**Comment by rourke750** [comment]
you use the txt file to authenticate pearls or you want the name to be logged when they are pearled?

**Comment by ariehkovler** [comment]
We use the txt file to check if people are currently pearled, as
/pplocateany in the console scrolls by too fast. Also easier for shell
scripts. So both

**Comment by rourke750** [comment]
Is adding another file that maps current uuids to player names which only has pearled players okay?

**Comment by ariehkovler** [comment]
That'd work though it might be less elegant.
