### ISSUE TITLE
/ppsd does not work

### ISSUE THREAD

**Issue by Grayyer** [Civcraft/PrisonPearl#29]
the /ppsetdist command does not allow the modification of the distance a pearled player can move away from their pearl.

**Comment by ttk2** [comment]
not sure how old this issue is, but its good to have one on it, please note
anything else that's broken

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/commit/5fb5858d6d49c2f49ddd0b2b277d0844b0343dc7
