### ISSUE TITLE
Console can't run console commands

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#32]
I tried running /ppcheck against a player and it stated that the console didn't have the right permission to do so. The code specifically locks this command to the console so the permission is rather redundant.

Commands that can be run by players or the console should explicitly grant the console permission. Humbug tags a permission group onto the console object and then adds the individual command permissions into that group (plugin.yml). For commands that are hard coded to only run in the console, the permission is unnecessary.

https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L2375

**Comment by jjj5311** [comment]
was this solved in the new version?

**Comment by ttk2** [comment]
its /pplocateany not /ppcheck right? or are they aliases, if they are then /pplocateany works perfectly.

**Comment by erocs** [comment]
They are different commands.

**Comment by ttk2** [comment]
yup still no perms to run it from the console.

**Comment by jjj5311** [comment]
#55

**Comment by suirad** [comment]
This can be closed.
