### ISSUE TITLE
Alt-ban logging

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#33]
Add a log of the number of bans loaded in BanManager.loadBanJournal.
Log a player's ban state as its seen by BanManager.onPlayerLogin.

**Comment by jjj5311** [comment]
Do you want to log all players ban states? or only those who are banned

**Comment by ttk2** [comment]
only those who are banned, all players is just too much

**Comment by erocs** [comment]
Any player who logs in I'd like to get a status reported out of that async
event for what decision it's making. We'd probably tone it down later.

Scenario, player logs in who should be alt banned but isn't denied and can
play. Confirmed there are two pearls for other accounts on the alt list.
The ban journal states the account is alt banned. Is there a login state
other then allowed that let them on? Did the async event not finish fast
enough to prevent the login?

**Comment by jjj5311** [comment]
Hmmm... i came up with a little bit of logging but not sure if the way i am doing it is good and/or if this is the right info. 

You can see it on my fix-33 branch

https://github.com/jjj5311/PrisonPearl/tree/fix-33

Here is the file outputs... is this what you want?

https://gist.github.com/jjj5311/8b693d8bad69c549dff9

**Comment by erocs** [comment]
You don't need to do all the file stuff. Just use PrisonPearlPlugin.log()
to log the entries into the server log.

One thing I'm curious about. Are there other enum values that allow a login
making this statement too permissive.  if (event.getLoginResult() !=
AsyncPlayerPreLoginEvent.Result.ALLOWED)

The rest you've logged is good, Alt-ban state vs. game-ban state. We
probably don't need to worry about ALLOW LOGIN and DENY LOGIN as we can
figure that out from the two ban states.

**Comment by jjj5311** [comment]
Okay sounds good I should be able to do that a little later

**Comment by erocs** [comment]
Thanks! Ttk2 let's stage this.

Also aeecea62

**Comment by ttk2** [comment]
stage the new jar or the version currently on Civtest?

**Comment by erocs** [comment]
New jar to CivTest / CivCraft (if this is the only change that would be
pushed to the main server)

**Comment by ttk2** [comment]
updated on civtest

**Comment by ttk2** [comment]
is this ready to go online

**Comment by ttk2** [comment]
is this ready to go online?

**Comment by erocs** [comment]
Yes, I don't know if there have been any other PP changes that haven't gone to the main server yet though.

**Comment by ttk2** [comment]
there does not seem to be anything of exceptional import, just pearl
someone and make sure that works I guess

**Comment by jjj5311** [comment]
It should only log their ban status and a few other things

**Comment by ttk2** [comment]
a few other changes are inbetween this and the currently running version,
so some testing is required.

**Comment by jjj5311** [comment]
This can be closed right?
