### ISSUE TITLE
New alt-bans for logged on players don't kick

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#35]
Accounts A and B are pearled. The player logs in C. The new alt list is passed to PrisonPearl, which decides that C should be alt banned. C is never kicked from the server though. C eventually logs off and attempts to log back in a few minutes later and is properly prevented from logging in by the alt-ban.

We need to figure out why new alt-bans don't cause an active player to be kicked.

**Comment by rourke750** [comment]
Does pp report that x players were now banned.

**Comment by erocs** [comment]
Relevant log entries from the player's session.

00:00:00 [INFO] XYZ[/z.z.z.z:zzzz] logged in
00:00:01 [INFO] [PrisonPearl] banning XYZ for having N imprisoned alts
00:00:01 [INFO] [PrisonPearl] XYZ still banned for having N imprisoned alts
00:01:20 [INFO] XYZ lost connection: Disconnected

**Comment by erocs** [comment]
Added log lines for their next login up in the previous comment.

**Comment by rourke750** [comment]
@erocs With the new namelayer can you see if this changes.

**Comment by suirad** [comment]
Status on this?

**Comment by suirad** [comment]
This should be fixed once prisonpearl integrates Civcraft/CBanManagement

**Comment by ttk2** [comment]
not sure if this got fixed, it must at least take effect on restart.

**Comment by Maxopoly** [comment]
From first hand experience I can confirm that this works, so I'll close it.
