### ISSUE TITLE
Pearl logging issue [[???]] was freed

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#36]
we get this 

2015-03-11 08:24:16 [INFO] [PrisonPearl] USERNAME [[???]] was freed

for several pearls and we can't figure out what if anything usual was happening to them.

**Comment by rourke750** [comment]
Is that the exact message without sanitation?

**Comment by ttk2** [comment]
2015-03-11 08:24:16 [INFO] [PrisonPearl] ttk2 [[???]] was freed

would be the exact message USERNAME is a sanitized username.

**Comment by suirad** [comment]
It doesn't look like its anything abnormal. From what i can tell from the line below, the "<pname> [???] was freed" message is supposed to have the coords of the player that was freed in that last part. But if they are offline, it just defaults to [???]. Non-issue, seen below: (PrisonPearlPlugin.java Line 718)
```java
String playerLoc = player != null ? serializeLocation(player.getLocation()) : "[???]";
```

**Comment by ttk2** [comment]
ok then closing, I would like to log choords even if offline though.
