### ISSUE TITLE
Automatic world border enforcement

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#39]
How do I enable it? the option was not generated in the config, AFIK it exists.

**Comment by rourke750** [comment]
uh, let me fix this

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/blob/master/config.yml#L25

**Comment by ttk2** [comment]
so now the config option will be generated?

**Comment by rourke750** [comment]
Check and see if its already there.  It should be.

**Comment by ttk2** [comment]
yes it is, can I just set it to 15000 then?

**Comment by rourke750** [comment]
yep.

**Comment by TealNerd** [comment]
i think we can close this one now

**Comment by rourke750** [comment]
https://github.com/Civcraft/PrisonPearl/pull/41
