### ISSUE TITLE
Need a way to store pearls outside of WB for white-listed chests or groups

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#45]

**Comment by rourke750** [comment]
I think groups would be best.  Guh, I hate how we are having all of plugins basically have a dependency on Namelayer.  I need to make it better as functioning as an api when group stuff is not needed,

**Comment by erocs** [comment]
It actually might be better to whitelist coordinates of a chest. That way if we absolutely had to we could exempt specific WB vaults or some such.

Having groups be exempt would be less hassle for administrative use though.

**Comment by rourke750** [comment]
@BlackXnt Want to handle this?

**Comment by BlackXnt** [comment]
Yes just came back home. I will see what I can do.

**Comment by BlackXnt** [comment]
https://github.com/Civcraft/PrisonPearl/pull/47
