### ISSUE TITLE
World Border Chest Enforcement

### ISSUE THREAD

**Issue by Cathonic** [Civcraft/PrisonPearl#49]
Some chests/locations are incorrectly identified as being beyond world border and are unable to store pearls after the 1.8 update. Prior to 1.8 they could and did successfully hold pearls.  

An example is this chest: http://imgur.com/fd2uGXh,lN8Bk1a,TgtInvU#2 . It can be stood on fully or to the side of it and prior to 1.8 it held pearls without problem. Now it gives the warning message and frees pearls held in it.

**Comment by rourke750** [comment]
We check through world border whether a chest is past world border or not.  Before we just did our own range calculation which wasnt as accurate as it didn't reflect the actual border.

**Comment by erocs** [comment]
@ttk2 Currently we only check the chest's location to see if it is in WB. Maybe this should be a little more extensive. Shall we switch to checking the four north / south / east / west adjacent blocks (not the chest itself) and if two of those are within the border the chest is considered to be within the border?

 X
XcX
 X

**Comment by ttk2** [comment]
we could do that, so this is now asking WB if the block is inside the
border? how does it define that?

**Comment by erocs** [comment]
Checks the center of the block against the calculated circle at radius from
the center of the map. that means if a chest's center position is just
outside WB the chest can't contain pearls. Doing this check would be closer
to the stated rules and would give a little leeway in this scenario.

**Comment by ttk2** [comment]
So then it sounds like we can leave it.

**Comment by erocs** [comment]
So keep the current behavior and not change to the two adjacent block check?

**Comment by ttk2** [comment]
I would say yes, its good enough and easy enough to explain.

**Comment by Cathonic** [comment]
Well leaving it as is isn't a very good solution. There's clearly some disagreement between the world border plugin and your calculation as people can walk down a tunnel on that line without being teleported. If a chest is beyond world border then people should not be able to stand on it. If people can stand on the chest it should not be beyond world border. The two plugins should agree.    


Obviously I'm upset because this change renders a 2500 diamond layer of our vault useless - we have to keep it there to stop people tunnelling, as it isn't beyond world border, but it no longer adds any layers to the vault as it's now behind the chest.

**Comment by ttk2** [comment]
if its being calculated the way described here you should not be able to
stand behind the chest correct?

**Comment by erocs** [comment]
The problem is people don't understand where to stand on it. If they stood directly in the center of the block they would have an accurate measurement. Nobody can do that though.

**Comment by Cathonic** [comment]
>if its being calculated the way described here you should not be able to stand behind the chest correct?    


If I move the chest away from world border one block (east, the only direction it can be moved and allow pearl storage) then I can stand behind the chest - in fact I can stand on every side. If the chest is in it's original spot (as pictured) I cannot stand behind it - but I can stand to the south and east of it, and on top.

**Comment by ttk2** [comment]
hmm, that's the official rule, I wonder then why so few chests had trouble
during the upgrade.

**Comment by Cathonic** [comment]
So are you keeping the plugin as it is?

**Comment by ttk2** [comment]
Still not sure, if it does not match previously described behavior then we
should change it, but if its hard to get it to match that behavior well we
should change the rule rather than do somthing hacky that could screw up
later .
