### ISSUE TITLE
Missing brackets causes improper pearl validation

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#52]
https://github.com/Civcraft/PrisonPearl/blob/master/src/com/untamedears/PrisonPearl/PrisonPearl.java#L310

The conditional "if (item.getDurability() == id)" doesn't use brackets to define a block. The immediate statement which would be executed if true is only logging into feedback. After the logging the "return HolderVerReason.IN_CHEST" is reached and always executed. This prevents "return HolderVerReason.DEFAULT;" from ever being reached if the pearl isn't actually within an inventory.

Please add some brackets to fix.

**Comment by ttk2** [comment]
on Civtest.
