### ISSUE TITLE
No Sharding Support

### ISSUE THREAD

**Issue by ttk2** [Civcraft/PrisonPearl#53]
Prisonpearl needs to support sharding, to that it will need to be possible to run pplocate across servers as well as handle freeing and summoning players to locations on other servers. 

This is probably going to require a pretty major overhaul, even worse it requires some features of BetterPortals to operate (carrying a pearl thorough a portal needs to work, pearl needs to not fail validation while in transit) 

Predicated requirements are as follows. 

* Pearl database instead of a flat file, unified across servers 

* Changes to validation code

* dependence on BetterPortals to handle moving players between servers.

**Comment by suirad** [comment]
Should i wait for the database support before i work on prison pearl?

**Comment by ttk2** [comment]
do it in whatever order you think is best, with Roruke out anything you
want to talk to him about a good deal should wait.

**Comment by rourke750** [comment]
Has mysql support and some sharding.  Each server will authenticate the pearls it knows it has.  It wont touch any other servers pearls.  Might need to create a global checker to make sure no pearls get lost.  What we do need is a conversion script from the text files to mysql.

**Comment by ttk2** [comment]
how about mercury calls? are those compatible with the way it works now?

**Comment by rourke750** [comment]
I manually added suriads changes to the master mercury repo.  Mercury is designed to handle any number of different things (can't think of what they are called) that we want.  Like it can support rabbit, reddis, and venus all depending on the config option that you choose while keeping the api the same.

**Comment by ttk2** [comment]
sounds good to me, so what else needs doing? Namelayer? Jukealert?

**Comment by rourke750** [comment]
Nothing really.  PrisonPearl will for sure give us the most troubles.

**Comment by ttk2** [comment]
ok then, testing environment setup is a go.
