### ISSUE TITLE
Add Missing TagManager for isCombatTag check on CombatTagManager class

### ISSUE THREAD

**Issue by rourke750** [Civcraft/PrisonPearl#65]
Currently only checks CombatTag not CombatTagPlus players if they are combat tagged.  Need to add the check.

**Comment by rourke750** [comment]
Use CombatTagPlus.getTagManager().isTagged(victim.getUniqueId())

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/PrisonPearl/pull/67
