### ISSUE TITLE
Pearls not properly releasing prisoners

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#66]
Text from report:

"Today I was showing a new player around my town and pearled them to demonstrate prison pearl and how it works. After doing that, while they were summoned i right clicked the pearl to free them. I happened to be facing them and the pearl acted like a regular pearl does, and it hit them and the pearl was gone. I killed them to see if I could pearl them again, but they died and there was no pearl created again. They are stuck in the end.

This actually happened to me yesterday as well with another new player. /ppl would tell them I held the pearl no matter where i was, even though i had no pearl. We tried re-logging, pearling me, killing me, etc. No prison pearl commands (/pps playername /ppr playername) worked for us. They stayed stuck in the end. Not sure if they've logged on today to see if reset fixed it."

**Comment by rourke750** [comment]
What is the console message for when they do /ppl, what does the verification message say.

**Comment by rourke750** [comment]
Also ask for more details, unable to reproduce.

**Comment by erocs** [comment]
You should have access to the ticket. I haven't checked the log for these particular instances.

**Comment by rourke750** [comment]
For now I want to attribute this to client visual bug.

**Comment by BlackXnt** [comment]
I can confirm I had this problem in the past. Player was freed after server restart.
