### ISSUE TITLE
Added softdependency to CBanManagement

### ISSUE THREAD

**Issue by rourke750** [Civcraft/PrisonPearl#68]
Make it so when pp loads it detects CBanManagement and if it finds it, it used that to do banning.

**Comment by ProgrammerDan** [comment]
Did this happen? If it didn't I can do this.

**Comment by rourke750** [comment]
Yes please.

**Comment by Maxopoly** [comment]
@ProgrammerDan Also please remember to poke jenkins to build CBanManagement at least once, so ttk can fix the ban thing tomorrow.

**Comment by ttk2** [comment]
got it, seems to have worked this time.
