### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by dagonzaros** [Civcraft/PrisonPearl#69]
http://puu.sh/kZcP8/8941ea93c3.png

Plugin appears to function completely correctly ingame however.

**Comment by rourke750** [comment]
On restarts do you get the first error?

**Comment by dagonzaros** [comment]
http://puu.sh/kZYCf/e6f206c33a.png

**Comment by dagonzaros** [comment]
This is a screenshot of the plugin starting up

**Comment by rourke750** [comment]
Are you using the mysql part in prisonpearl?

**Comment by dagonzaros** [comment]
Yes it is enabled, should we try disabling it?

**Comment by rourke750** [comment]
Yes.
