### ISSUE TITLE
ppsummon in confined space doesn't summon the prisoner in close proximity

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#70]
Summoning a person's pearl in a confined area like a cave sometimes causes them to summon 50 blocks above you and instantly cause the person to start taking damage.

**Comment by rourke750** [comment]
Nothing really new.  Just would have to do ppreturn and then find a more open space.

**Comment by TealNerd** [comment]
why not just summon someone directly in the same block as the person summoning them?

**Comment by ttk2** [comment]
that doesn't really look good, if we needed to guarantee this  feature
worked and it was used super often we would probably take the compromise
and do that, but since its mostly a 'nice to have' feature we would like it
to look good when being used.

**Comment by rourke750** [comment]
New rewrite, should have different behavior.
