### ISSUE TITLE
PP Ignores loss of Combattag when awarding pearl

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/PrisonPearl#74]
So, an issue I recently became aware of causes significant player confusion.

Damagelogger has its own internal mechanism for "forgetting" prior damage -- it's tied to TPS, so "takes longer" when the server is running at lower TPS -- but this leads to player confusion. 

Case study:

* Players A and B engage in combat. 
* Player A breaks off to escape player B, who was "winning". 
* While chasing player A, combat tag on player B ends.
* 10-20 seconds later, still without combat tag, player B falls and dies. 
* Player A is instantly awarded player B's pearl.

I propose that we add a check in the player death routine, where IIF combattag or CTP is available, we check first if the player who died was combat-tagged before awarding a pearl.

This would significantly reduce player confusion and resulting modmails in situations similar to those described above.

A more extreme variant, for instance, is that if TPS is around 10, a player's death a full minute after any combat -- could still result in an awarded pearl, under the current system.

**Comment by ProgrammerDan** [comment]
Just got reports that ~3 people were impacted by this issue several minutes after fighting had concluded when they were blown up by a creeper.

**Comment by TealNerd** [comment]
@ProgrammerDan you fixed this, should the issue be closed?
