### ISSUE TITLE
Players spawn improperly when relogging after being freed

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#77]
Two instances where someone was released from their pearl, went about their business and logged for the night. Next time upon logging in they seem to spawn where the logged out, but then they get respawned back into the end and all their equipment drops where they were, due to the end's equipment restrictions.

**Comment by Maxopoly** [comment]
Afaik in each case there was also the server restart inbetween them getting freed and then logging in again in the end.

**Comment by rourke750** [comment]
I think this was just a fluke that might have occurred due to the restore from earlier.  Not tuesday's.

**Comment by erocs** [comment]
This was the 14th. The first restore was the 15th.
