### ISSUE TITLE
Pearls only identify to a world's name

### ISSUE THREAD

**Issue by erocs** [Civcraft/PrisonPearl#88]
In a sharded environment, the shard name should be included in the pearl record. Also, instead of relying on the world name, which could overlap between shards, it should probably use the world's unique ID.

**Comment by rourke750** [comment]
For which part would this be needed?  There are two config options one for
server and one for world name when dealing with prisoners.

**Comment by erocs** [comment]
I was looking at the DB table.

**Comment by rourke750** [comment]
That's important.

**Comment by rourke750** [comment]
We should add a server column too.

**Comment by erocs** [comment]
That'd be the shard name, yes.
