### ISSUE TITLE
Potentially Drop Support for CombatTag

### ISSUE THREAD

**Issue by KillerSmurf** [Civcraft/PrisonPearl#99]
Right now we are supporting CombatTag, and CombatTag+.

Based on the information I got from @Maxopoly CT is no longer being worked on.

It's all fine and good to want to support multiple CT versions.
But I'd say there is no reason to continue to support a deprecated plugin and we should drop it and only support CT+, since it is currently being updated and worked on.

@rourke750 @ProgrammerDan

**Comment by ProgrammerDan** [comment]
I'd be fine with this.

**Comment by KillerSmurf** [comment]
Based on this page: https://www.spigotmc.org/resources/combat-tag.3182/updates

It looks like CombatTag was last updated for 1.8.3. Not sure what version the server is running officially.

But even if it doesn't affect us right now it will in the near future potentially.

**Comment by Maxopoly** [comment]
I support it

**Comment by rourke750** [comment]
might as well drop it.
